### ISSUE TITLE
ChunkWE

### ISSUE THREAD

**Issue by Aericio** [thebigsmileXD/MagicWE#9]
I was the wand to world edit a 90x90 region, and for some reason after I world edited, it loaded 9000 chunks.
![image](https://cloud.githubusercontent.com/assets/16523741/15809112/ef13d3f6-2b24-11e6-9ab4-e663aa0c2f1b.png)
It was 9,000+ chunks before, but since I took the /status a bit late, it was already going down. Glitch? :(
I'll be going back to WorldEditArt for now... it's faster and doesn't load 9000 chunks. My server only uses 1,500 - 2,000 chunks from players, but never 9,000 chunks. If you wish, I will give you a debug level  2.

**Comment by thebigsmileXD** [comment]
Well, i only see 5981 / 5887 chunks loaded on your screenshot.
MagicWE uses setBlockIdAt instead of setBlock, due to being WAY faster.
I am pretty sure its the fault of something else that it loads chunks, maybe a core bug, but not the plugin.
setBlockIdAt doesnt even call block updates neither saves chunks.

**Comment by Aericio** [comment]
It went down since I didn't do /status in time. What do you mean core bug?? ClearSky?

**Comment by thebigsmileXD** [comment]
Maybe
